"""new table

Revision ID: 0b36188ae3c6
Revises: c6132f0deb70
Create Date: 2026-05-25 01:06:38.471131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0b36188ae3c6'
down_revision: Union[str, None] = 'c6132f0deb70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliable_banks',
    sa.Column('bank_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('bank_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliable_banks')
    # ### end Alembic commands ###
