"""initial

Revision ID: 4998a5e45af5
Revises: 
Create Date: 2026-05-22 23:05:31.399868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4998a5e45af5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('bank_type', sa.String(length=100), nullable=False),
    sa.Column('start_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('bank_name')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('credit_transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('first_payment', sa.Date(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('interest', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_transactions')
    op.drop_table('transactions')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
