"""okay

Revision ID: 5c82e3f7f27c
Revises: c2a2cfad97df
Create Date: 2026-05-27 04:18:28.018275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c82e3f7f27c'
down_revision: Union[str, None] = 'c2a2cfad97df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'start_value',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('transactions', 'value',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'value',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'start_value',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
