"""relationship accounts and banks

Revision ID: acfb8b4d6b45
Revises: 0b36188ae3c6
Create Date: 2026-05-25 01:11:21.195079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'acfb8b4d6b45'
down_revision: Union[str, None] = '0b36188ae3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('bank_id', sa.Integer(), nullable=False))
    op.drop_column('bank_accounts', 'bank_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('bank_accounts', 'bank_id')
    # ### end Alembic commands ###
