"""relationship accounts and banks

Revision ID: c2a2cfad97df
Revises: acfb8b4d6b45
Create Date: 2026-05-25 01:12:36.516935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2a2cfad97df'
down_revision: Union[str, None] = 'acfb8b4d6b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
