"""creating constraints in accounts

Revision ID: c6132f0deb70
Revises: dabfe2d642df
Create Date: 2026-05-25 00:53:34.035856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c6132f0deb70'
down_revision: Union[str, None] = 'dabfe2d642df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('account_name', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('bank_accounts_bank_name_key'), 'bank_accounts', type_='unique')
    op.create_unique_constraint(None, 'bank_accounts', ['account_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_accounts', type_='unique')
    op.create_unique_constraint(op.f('bank_accounts_bank_name_key'), 'bank_accounts', ['bank_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('bank_accounts', 'account_name')
    # ### end Alembic commands ###
