"""rename columns in bank_account

Revision ID: dabfe2d642df
Revises: ea7e2ca54b1c
Create Date: 2026-05-25 00:23:57.800615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dabfe2d642df'
down_revision: Union[str, None] = 'ea7e2ca54b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('bank_accounts', 'bank_type', new_column_name='account_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('bank_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('bank_accounts', 'created_at')
    op.drop_column('bank_accounts', 'account_type')
    # ### end Alembic commands ###
