"""big changes kekw

Revision ID: ea7e2ca54b1c
Revises: 4998a5e45af5
Create Date: 2026-05-24 06:02:49.092283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea7e2ca54b1c'
down_revision: Union[str, None] = '4998a5e45af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_transactions')
    op.alter_column('bank_accounts', 'start_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('transactions', 'value',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'value',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'start_value',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.create_table('credit_transactions',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_payment', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('installments', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interest', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], name=op.f('credit_transactions_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('credit_transactions_pkey'))
    )
    # ### end Alembic commands ###
